#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon May  9 22:30:54 2022

@author: kushgupta
"""

import cv2 
import glob
import sys
import os

directory = '/Users/kushgupta/Downloads/Extracted_faces/real'
images_path=glob.glob('/Users/kushgupta/Downloads/Task_2_3/evaluation/real/id*/*.jpg')
images_path.sort()
count_img=1
count_face=1
for image_path in images_path:
    image = cv2.imread(image_path)
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    
    faceCascade = cv2.CascadeClassifier(cv2.data.haarcascades + "haarcascade_frontalface_default.xml")
    faces = faceCascade.detectMultiScale(
        image,
        scaleFactor=1.3,
        minNeighbors=2,
        minSize=(30, 30)
    )
    
    #print("[INFO] Found {0} Faces.".format(len(faces)))
    count_img+=1
    for (x, y, w, h) in faces:
        #cv2.rectangle(image, (x, y), (x + w, y + h), (0, 255, 0), 2)
        h=h+10 
        w=w+10
        roi_color = image[y:y + h, x:x + w]
        #print("[INFO] Object found. Saving locally.")
        os.chdir(directory) 
        cv2.imwrite('real'+str(count_face) + '_faces.jpg', roi_color)
        #cv2.imwrite('fake'+str(count_face) + '_faces.jpg', roi_color)
        count_face=count_face+1
        #cv2.imshow('window', roi_color)
        #cv2.waitKey(1)
    #status = cv2.imwrite('faces_detected.jpg', image)
    #print("[INFO] Image faces_detected.jpg written to filesystem: ", status)